# db.py
from __future__ import annotations

import os
from pathlib import Path
from datetime import datetime

import pandas as pd
import streamlit as st
from sqlalchemy import create_engine, text

DB_PATH = Path(__file__).resolve().parent / "finance.db"


# -----------------------------------------
# CONEXÃO (Supabase se tiver DATABASE_URL, senão SQLite local)
# -----------------------------------------
def _get_db_url() -> str:
    if "DATABASE_URL" in st.secrets:
        return str(st.secrets["DATABASE_URL"]).strip()
    env = os.getenv("DATABASE_URL")
    if env:
        return env.strip()
    return f"sqlite:///{DB_PATH}"


def _is_postgres(url: str) -> bool:
    return url.startswith("postgresql://") or url.startswith("postgres://")


_DB_URL = _get_db_url()
IS_PG = _is_postgres(_DB_URL)

ENGINE = create_engine(
    _DB_URL,
    pool_pre_ping=True,
    pool_recycle=300,
)


def ping_db() -> tuple[bool, str]:
    try:
        with ENGINE.connect() as conn:
            v = conn.execute(text("select 1")).scalar()
        return (v == 1), "ok"
    except Exception as e:
        return False, str(e)


def _now_iso() -> str:
    return datetime.utcnow().isoformat()


# -----------------------------------------
# INIT DB (cria tabelas)
# -----------------------------------------
def init_db():
    with ENGINE.begin() as conn:
        if IS_PG:
            # =========================
            # POSTGRES (Supabase)
            # =========================
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS transactions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    date DATE NOT NULL,
                    description TEXT NOT NULL,
                    type TEXT NOT NULL CHECK (type IN ('entrada','saida')),
                    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
                    category TEXT NOT NULL,
                    paid SMALLINT NOT NULL CHECK (paid IN (0,1)),
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );
            """))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_tx_date ON transactions(date);"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_tx_paid ON transactions(paid);"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_tx_type ON transactions(type);"))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS savings_goal_v2 (
                    id SMALLINT PRIMARY KEY CHECK (id = 1),
                    target_amount NUMERIC(12,2),
                    due_date DATE,
                    n_deposits INT
                );
            """))
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS savings_deposits_v2 (
                    n INT PRIMARY KEY,
                    done SMALLINT NOT NULL DEFAULT 0 CHECK (done IN (0,1))
                );
            """))
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS savings_overrides_v2 (
                    n INT PRIMARY KEY,
                    amount NUMERIC(12,2) NOT NULL
                );
            """))
            conn.execute(text("""
                INSERT INTO savings_goal_v2 (id, target_amount, due_date, n_deposits)
                VALUES (1, NULL, NULL, NULL)
                ON CONFLICT (id) DO NOTHING;
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS savings_tx_link_v2 (
                    n INT PRIMARY KEY,
                    tx_id BIGINT NOT NULL
                );
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS cashflow_adjustments (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    data DATE NOT NULL,
                    valor NUMERIC(12,2) NOT NULL,
                    descricao TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );
            """))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_adj_data ON cashflow_adjustments(data);"))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS debts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    credor TEXT NOT NULL,
                    descricao TEXT,
                    valor NUMERIC(12,2) NOT NULL,
                    vencimento DATE,
                    prioridade INT NOT NULL DEFAULT 1,
                    quitada SMALLINT NOT NULL DEFAULT 0 CHECK (quitada IN (0,1)),
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );
            """))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_debts_quitada ON debts(quitada);"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_debts_prioridade ON debts(prioridade);"))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS notes (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    titulo TEXT,
                    texto TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );
            """))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_notes_updated ON notes(updated_at);"))

        else:
            # =========================
            # SQLITE (local)
            # =========================
            conn.execute(text("PRAGMA foreign_keys = ON;"))
            conn.execute(text("PRAGMA journal_mode = WAL;"))
            conn.execute(text("PRAGMA synchronous = NORMAL;"))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS transactions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    date TEXT NOT NULL,
                    description TEXT NOT NULL,
                    type TEXT NOT NULL CHECK(type IN ('entrada','saida')),
                    amount REAL NOT NULL CHECK(amount >= 0),
                    category TEXT NOT NULL,
                    paid INTEGER NOT NULL CHECK(paid IN (0,1)),
                    created_at TEXT NOT NULL
                );
            """))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_tx_date ON transactions(date);"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_tx_paid ON transactions(paid);"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_tx_type ON transactions(type);"))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS savings_goal_v2 (
                    id INTEGER PRIMARY KEY CHECK (id = 1),
                    target_amount REAL,
                    due_date TEXT,
                    n_deposits INTEGER
                );
            """))
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS savings_deposits_v2 (
                    n INTEGER PRIMARY KEY,
                    done INTEGER NOT NULL DEFAULT 0
                );
            """))
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS savings_overrides_v2 (
                    n INTEGER PRIMARY KEY,
                    amount REAL NOT NULL
                );
            """))
            conn.execute(text("""
                INSERT OR IGNORE INTO savings_goal_v2 (id, target_amount, due_date, n_deposits)
                VALUES (1, NULL, NULL, NULL);
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS savings_tx_link_v2 (
                    n INTEGER PRIMARY KEY,
                    tx_id INTEGER NOT NULL
                );
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS cashflow_adjustments (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    data TEXT NOT NULL,
                    valor REAL NOT NULL,
                    descricao TEXT,
                    created_at TEXT NOT NULL
                );
            """))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_adj_data ON cashflow_adjustments(data);"))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS debts (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    credor TEXT NOT NULL,
                    descricao TEXT,
                    valor REAL NOT NULL,
                    vencimento TEXT,
                    prioridade INTEGER NOT NULL DEFAULT 1,
                    quitada INTEGER NOT NULL DEFAULT 0,
                    created_at TEXT NOT NULL
                );
            """))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_debts_quitada ON debts(quitada);"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_debts_prioridade ON debts(prioridade);"))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS notes (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    titulo TEXT,
                    texto TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );
            """))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_notes_updated ON notes(updated_at);"))


# -----------------------------------------
# TRANSACTIONS
# -----------------------------------------
def add_transaction(date_: str, description: str, ttype: str, amount: float, category: str, paid: int):
    if IS_PG:
        q = text("""
            INSERT INTO transactions (date, description, type, amount, category, paid)
            VALUES (:date, :description, :type, :amount, :category, :paid)
        """)
        params = {
            "date": str(date_),
            "description": str(description).strip(),
            "type": str(ttype).strip().lower(),
            "amount": float(amount),
            "category": str(category).strip() if str(category).strip() else "Outros",
            "paid": int(paid),
        }
    else:
        q = text("""
            INSERT INTO transactions (date, description, type, amount, category, paid, created_at)
            VALUES (:date, :description, :type, :amount, :category, :paid, :created_at)
        """)
        params = {
            "date": str(date_),
            "description": str(description).strip(),
            "type": str(ttype).strip().lower(),
            "amount": float(amount),
            "category": str(category).strip() if str(category).strip() else "Outros",
            "paid": int(paid),
            "created_at": _now_iso(),
        }

    with ENGINE.begin() as conn:
        conn.execute(q, params)


def fetch_transactions(date_start: str | None = None, date_end: str | None = None) -> pd.DataFrame:
    q = """
        SELECT id, date, description, type, amount, category, paid
        FROM transactions
        WHERE 1=1
    """
    params = {}
    if date_start:
        q += " AND date >= :start"
        params["start"] = str(date_start)
    if date_end:
        q += " AND date <= :end"
        params["end"] = str(date_end)

    q += " ORDER BY date DESC, id DESC"

    with ENGINE.connect() as conn:
        df = pd.read_sql_query(text(q), conn, params=params)

    if df.empty:
        return pd.DataFrame(columns=["id","date","description","type","amount","category","paid"])

    df["amount"] = pd.to_numeric(df["amount"], errors="coerce").fillna(0.0)
    df["paid"] = pd.to_numeric(df["paid"], errors="coerce").fillna(0).astype(int)
    df["type"] = df["type"].astype(str).str.strip().str.lower()
    df["category"] = df["category"].astype(str).fillna("Outros")
    return df


def delete_transaction(tx_id: int):
    with ENGINE.begin() as conn:
        # 1) apaga links do desafio que apontam pra esse lançamento
        conn.execute(
            text("DELETE FROM savings_tx_link_v2 WHERE tx_id = :id"),
            {"id": int(tx_id)}
        )

        # 2) agora apaga o lançamento
        conn.execute(
            text("DELETE FROM transactions WHERE id = :id"),
            {"id": int(tx_id)}
        )


def update_transactions_bulk(df_updates: pd.DataFrame):
    if df_updates is None or df_updates.empty:
        return

    with ENGINE.begin() as conn:
        for _, r in df_updates.iterrows():
            conn.execute(
                text("""
                    UPDATE transactions
                    SET date=:date, description=:description, type=:type, amount=:amount, category=:category, paid=:paid
                    WHERE id=:id
                """),
                {
                    "date": str(r["date"]),
                    "description": str(r["description"]).strip(),
                    "type": str(r["type"]).strip().lower(),
                    "amount": float(r["amount"]),
                    "category": str(r["category"]).strip() if str(r["category"]).strip() else "Outros",
                    "paid": int(r["paid"]),
                    "id": int(r["id"]),
                },
            )


# -----------------------------------------
# AJUSTES DO FLUXO (SIMULAÇÃO)
# -----------------------------------------
def add_cashflow_adjustment(data: str, valor: float, descricao: str | None = None):
    if IS_PG:
        q = text("""
            INSERT INTO cashflow_adjustments (data, valor, descricao)
            VALUES (:data, :valor, :descricao)
        """)
        params = {"data": str(data), "valor": float(valor), "descricao": (descricao or "").strip()}
    else:
        q = text("""
            INSERT INTO cashflow_adjustments (data, valor, descricao, created_at)
            VALUES (:data, :valor, :descricao, :created_at)
        """)
        params = {"data": str(data), "valor": float(valor), "descricao": (descricao or "").strip(), "created_at": _now_iso()}

    with ENGINE.begin() as conn:
        conn.execute(q, params)


def fetch_cashflow_adjustments(date_start: str, date_end: str) -> pd.DataFrame:
    with ENGINE.connect() as conn:
        df = pd.read_sql_query(
            text("""
                SELECT id, data, valor, descricao
                FROM cashflow_adjustments
                WHERE data >= :start AND data <= :end
                ORDER BY data ASC, id ASC
            """),
            conn,
            params={"start": str(date_start), "end": str(date_end)},
        )

    if df.empty:
        return pd.DataFrame(columns=["id","data","valor","descricao"])

    df["valor"] = pd.to_numeric(df["valor"], errors="coerce").fillna(0.0)
    return df


def delete_cashflow_adjustment(adj_id: int):
    with ENGINE.begin() as conn:
        conn.execute(text("DELETE FROM cashflow_adjustments WHERE id=:id"), {"id": int(adj_id)})


# -----------------------------------------
# DÍVIDAS
# -----------------------------------------
def add_debt(credor: str, descricao: str, valor: float, vencimento: str | None, prioridade: int):
    if IS_PG:
        q = text("""
            INSERT INTO debts (credor, descricao, valor, vencimento, prioridade, quitada)
            VALUES (:credor, :descricao, :valor, :vencimento, :prioridade, 0)
        """)
        params = {
            "credor": credor.strip(),
            "descricao": (descricao or "").strip(),
            "valor": float(valor),
            "vencimento": None if not vencimento else str(vencimento),
            "prioridade": int(prioridade),
        }
    else:
        q = text("""
            INSERT INTO debts (credor, descricao, valor, vencimento, prioridade, quitada, created_at)
            VALUES (:credor, :descricao, :valor, :vencimento, :prioridade, 0, :created_at)
        """)
        params = {
            "credor": credor.strip(),
            "descricao": (descricao or "").strip(),
            "valor": float(valor),
            "vencimento": None if not vencimento else str(vencimento),
            "prioridade": int(prioridade),
            "created_at": _now_iso(),
        }

    with ENGINE.begin() as conn:
        conn.execute(q, params)


def fetch_debts(show_quitadas: bool = False) -> pd.DataFrame:
    if IS_PG:
        q = """
            SELECT id, credor, descricao, valor, vencimento, prioridade, quitada, created_at
            FROM debts
        """
        if not show_quitadas:
            q += " WHERE quitada = 0"
        q += " ORDER BY prioridade ASC, COALESCE(vencimento, DATE '9999-12-31') ASC, id DESC"
    else:
        q = """
            SELECT id, credor, descricao, valor, vencimento, prioridade, quitada, created_at
            FROM debts
        """
        if not show_quitadas:
            q += " WHERE quitada = 0"
        q += " ORDER BY prioridade ASC, COALESCE(vencimento,'9999-12-31') ASC, id DESC"

    with ENGINE.connect() as conn:
        df = pd.read_sql_query(text(q), conn)

    if df.empty:
        return pd.DataFrame(columns=["id","credor","descricao","valor","vencimento","prioridade","quitada","created_at"])

    df["valor"] = pd.to_numeric(df["valor"], errors="coerce").fillna(0.0)
    df["quitada"] = pd.to_numeric(df["quitada"], errors="coerce").fillna(0).astype(int)
    return df


def mark_debt_paid(debt_id: int, paid: bool):
    with ENGINE.begin() as conn:
        conn.execute(
            text("UPDATE debts SET quitada=:q WHERE id=:id"),
            {"q": 1 if paid else 0, "id": int(debt_id)},
        )


def delete_debt(debt_id: int):
    with ENGINE.begin() as conn:
        conn.execute(text("DELETE FROM debts WHERE id=:id"), {"id": int(debt_id)})


# -----------------------------------------
# DESAFIO (v2) - COMPLETO
# -----------------------------------------
def _min_n_for_target(target: float) -> int:
    import math
    if target <= 0:
        return 1
    n = int((math.sqrt(1 + 8 * target) - 1) / 2)
    if n * (n + 1) / 2 < target:
        n += 1
    return max(1, n)


def set_savings_goal_v2(target_amount: float, due_date: str | None):
    target_amount = float(target_amount)
    n = _min_n_for_target(target_amount)

    with ENGINE.begin() as conn:
        conn.execute(
            text("""
                UPDATE savings_goal_v2
                SET target_amount=:t, due_date=:d, n_deposits=:n
                WHERE id=1
            """),
            {"t": target_amount, "d": due_date, "n": int(n)},
        )

        rows = conn.execute(text("SELECT n, done FROM savings_deposits_v2")).mappings().all()
        existing = {int(r["n"]): int(r["done"]) for r in rows}

        conn.execute(text("DELETE FROM savings_deposits_v2 WHERE n > :n"), {"n": int(n)})
        conn.execute(text("DELETE FROM savings_overrides_v2 WHERE n > :n"), {"n": int(n)})
        conn.execute(text("DELETE FROM savings_tx_link_v2 WHERE n > :n"), {"n": int(n)})

        for i in range(1, n + 1):
            if i not in existing:
                conn.execute(text("INSERT INTO savings_deposits_v2 (n, done) VALUES (:n, 0)"), {"n": int(i)})


def get_savings_goal_v2():
    with ENGINE.connect() as conn:
        row = conn.execute(
            text("SELECT target_amount, due_date, n_deposits FROM savings_goal_v2 WHERE id=1")
        ).mappings().first()
    if not row:
        return None, None, None
    return row["target_amount"], row["due_date"], row["n_deposits"]


def fetch_savings_deposits_v2_with_amount() -> pd.DataFrame:
    with ENGINE.connect() as conn:
        df = pd.read_sql_query(text("""
            SELECT
              d.n,
              d.done,
              COALESCE(o.amount, d.n) AS amount
            FROM savings_deposits_v2 d
            LEFT JOIN savings_overrides_v2 o ON o.n = d.n
            ORDER BY d.n
        """), conn)

    if df.empty:
        return pd.DataFrame(columns=["n","done","amount"])

    df["done"] = pd.to_numeric(df["done"], errors="coerce").fillna(0).astype(int)
    df["amount"] = pd.to_numeric(df["amount"], errors="coerce").fillna(0.0)
    return df


def toggle_savings_deposit_v2(n: int, done: bool):
    with ENGINE.begin() as conn:
        conn.execute(
            text("UPDATE savings_deposits_v2 SET done=:d WHERE n=:n"),
            {"d": 1 if done else 0, "n": int(n)},
        )


def set_savings_override_v2(n: int, amount: float | None):
    with ENGINE.begin() as conn:
        if amount is None:
            conn.execute(text("DELETE FROM savings_overrides_v2 WHERE n=:n"), {"n": int(n)})
        else:
            if IS_PG:
                conn.execute(text("""
                    INSERT INTO savings_overrides_v2 (n, amount)
                    VALUES (:n, :a)
                    ON CONFLICT (n) DO UPDATE SET amount=EXCLUDED.amount
                """), {"n": int(n), "a": float(amount)})
            else:
                conn.execute(text("""
                    INSERT INTO savings_overrides_v2 (n, amount)
                    VALUES (:n, :a)
                    ON CONFLICT(n) DO UPDATE SET amount=excluded.amount
                """), {"n": int(n), "a": float(amount)})


def reset_savings_marks_v2():
    with ENGINE.begin() as conn:
        conn.execute(text("UPDATE savings_deposits_v2 SET done=0"))
        conn.execute(text("DELETE FROM savings_tx_link_v2"))


def clear_savings_goal_v2():
    with ENGINE.begin() as conn:
        conn.execute(text("UPDATE savings_goal_v2 SET target_amount=NULL, due_date=NULL, n_deposits=NULL WHERE id=1"))
        conn.execute(text("DELETE FROM savings_deposits_v2"))
        conn.execute(text("DELETE FROM savings_overrides_v2"))
        conn.execute(text("DELETE FROM savings_tx_link_v2"))


def create_desafio_transaction(date_: str, n: int, amount: float):
    with ENGINE.begin() as conn:
        row = conn.execute(
            text("SELECT tx_id FROM savings_tx_link_v2 WHERE n=:n"),
            {"n": int(n)}
        ).mappings().first()
        if row:
            return int(row["tx_id"])

        if IS_PG:
            res = conn.execute(text("""
                INSERT INTO transactions (date, description, type, amount, category, paid)
                VALUES (:date, :desc, 'entrada', :amount, 'Desafio', 1)
                RETURNING id
            """), {"date": str(date_), "desc": f"Desafio - Depósito #{int(n)}", "amount": float(amount)})
            tx_id = int(res.scalar_one())
        else:
            conn.execute(text("""
                INSERT INTO transactions (date, description, type, amount, category, paid, created_at)
                VALUES (:date, :desc, 'entrada', :amount, 'Desafio', 1, :created_at)
            """), {"date": str(date_), "desc": f"Desafio - Depósito #{int(n)}", "amount": float(amount), "created_at": _now_iso()})
            tx_id = int(conn.execute(text("SELECT last_insert_rowid()")).scalar())

        conn.execute(
            text("""
                INSERT INTO savings_tx_link_v2 (n, tx_id)
                VALUES (:n, :tx)
            """),
            {"n": int(n), "tx": int(tx_id)},
        )
        return int(tx_id)


def delete_desafio_transaction(n: int):
    with ENGINE.begin() as conn:
        row = conn.execute(
            text("SELECT tx_id FROM savings_tx_link_v2 WHERE n=:n"),
            {"n": int(n)}
        ).mappings().first()
        if not row:
            return
        tx_id = int(row["tx_id"])
        conn.execute(text("DELETE FROM transactions WHERE id=:id"), {"id": tx_id})
        conn.execute(text("DELETE FROM savings_tx_link_v2 WHERE n=:n"), {"n": int(n)})


# -----------------------------------------
# BLOCO DE NOTAS
# -----------------------------------------
def add_note(titulo: str, texto: str):
    if IS_PG:
        q = text("""
            INSERT INTO notes (titulo, texto, created_at, updated_at)
            VALUES (:t, :x, NOW(), NOW())
        """)
        params = {"t": str(titulo or "").strip(), "x": str(texto or "").strip()}
    else:
        now = _now_iso()
        q = text("""
            INSERT INTO notes (titulo, texto, created_at, updated_at)
            VALUES (:t, :x, :c, :u)
        """)
        params = {"t": str(titulo or "").strip(), "x": str(texto or "").strip(), "c": now, "u": now}

    with ENGINE.begin() as conn:
        conn.execute(q, params)


def fetch_notes() -> pd.DataFrame:
    with ENGINE.connect() as conn:
        df = pd.read_sql_query(
            text("""
                SELECT id, titulo, texto, created_at, updated_at
                FROM notes
                ORDER BY updated_at DESC, id DESC
            """),
            conn,
        )

    if df.empty:
        return pd.DataFrame(columns=["id","titulo","texto","created_at","updated_at"])

    df["created_at"] = pd.to_datetime(df["created_at"], errors="coerce").dt.strftime("%d/%m/%Y %H:%M")
    df["updated_at"] = pd.to_datetime(df["updated_at"], errors="coerce").dt.strftime("%d/%m/%Y %H:%M")
    return df


def update_note(note_id: int, titulo: str, texto: str):
    if IS_PG:
        q = text("""
            UPDATE notes
            SET titulo=:t, texto=:x, updated_at=NOW()
            WHERE id=:id
        """)
        params = {"t": str(titulo or "").strip(), "x": str(texto or "").strip(), "id": int(note_id)}
    else:
        q = text("""
            UPDATE notes
            SET titulo=:t, texto=:x, updated_at=:u
            WHERE id=:id
        """)
        params = {"t": str(titulo or "").strip(), "x": str(texto or "").strip(), "u": _now_iso(), "id": int(note_id)}

    with ENGINE.begin() as conn:
        conn.execute(q, params)


def delete_note(note_id: int):
    with ENGINE.begin() as conn:
        conn.execute(text("DELETE FROM notes WHERE id=:id"), {"id": int(note_id)})
